repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: backend/
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["backend/app"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        files: backend/
        exclude: backend/app/tests
        args: [-r]
  - repo: github.com/pre-commit/mirrors-prettier 
    rev: 2.6.2
    hooks:
    -   id: prettier 
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 8.15.0
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@4.15.0
        -   eslint-config-google@0.7.1
        -   eslint-loader@1.6.1
        -   eslint-plugin-react@6.10.3
        -   babel-eslint@6.1.2
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-vet
      - id: go-lint
      - id: go-imports
      - id: go-cyclo
        args: [-over=15]
      - id: validate-toml
      - id: no-go-testing
      - id: golangci-lint
      - id: go-critic
      - id: go-unit-tests
      - id: go-build
      - id: go-mod-tidy