version: "3.8"
services:
  mongo:
    image: mongo:5.0.8
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 1s
      timeout: 10s
      retries: 5
  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  dns:
    build: dns
    restart: always
    command: ./dns
    ports:
      - 153:153
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
  api:
    build: api
    restart: always
    ports:
      - 8000:80
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy
  frontend:
    build: frontend
    restart: always
    command: ng serve --port 80
    ports:
      - 80:80
    depends_on:
      - api
