name: DNS CI
on:
  push:
    branches:
      - "**"
jobs:
  linters:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dns
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Install packages
        run: go install
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Run tests
        run: go test .
        working-directory: ./dns
