name: Frontend CI
on:
  push:
    branches:
      - "**"
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker
        run: docker build --tag=dns-frontend:latest ./dns/
      - name: Run Angular linter
        run: docker run dns-frontend bash -c "ng lint"
      - name: Run unit tests
        run: docker run dns-frontend bash -c "npm ci; ng test --no-watch --no-progress --browsers=ChromeHeadlessCI"
      - name: Run E2E tests
        run: docker run dns-frontend bash -c "ng e2e"
