name: Frontend CI
on:
  push:
    branches:
      - "**"
jobs:
  docker-build:
    needs: linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build docker
        run: docker build --tag=dns-frontend:latest ./dns/

  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Verify dependencies
        run: docker run dns-frontend bash -c "ng e2e"
      - name: Build
        run: docker run dns-frontend bash -c "ng lint"
      - name: Run go vet
        run: docker run dns-frontend bash -c "go vet ./..."
      - name: Install staticcheck
        run: docker run dns-frontend bash -c "go install honnef.co/go/tools/cmd/staticcheck@latest"
      - name: Run staticcheck
        run: docker run dns-frontend bash -c "staticcheck ./..."
      - name: Install golint
        run: docker run dns-frontend bash -c "go install golang.org/x/lint/golint@latest"
      - name: Run golint
        run: docker run dns-frontend bash -c "golint ./..."
  tests:
    needs: linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: docker run dns-frontend bash -c "npm ci; ng test --no-watch --no-progress --browsers=ChromeHeadlessCI"